layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: lingqi-meng-1280a6182
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://github.com/lingqime
  # youtube: your_username

topics:
  - name: Python
    web_url: https://www.python.org
    image_url: icons/python icon.jpg

  - name: Javascript
    web_url: https://developer.mozilla.org/en-US/docs/Web/JavaScript
    image_url: icons/JS icon.jpg

  - name: C++
    web_url: https://learn.microsoft.com/en-us/cpp/cpp/?view=msvc-170
    image_url: icons/Cpp icon.png
